export const bahasa = [
        {
            hrmi: "Minggu",
            hrse: "Senin",
            hrsel: "Selasa",
            hrrb: "Rabu",
            hrkm: "Kamis",
            hrju: "Jumat",
            hrsa: "Sabtu",
            stok: "Stok",
            pembelian: "Pembelian",
            penjualan: "Penjualan",
            dtbrg: "Data Barang",
            rkmn: "Rekaman",
            rcpem: "Rekaman Pembelian",
            rcpen: "Rekaman Penjualan",
            mskn: "Masukan",
            ibar: "ID Barang",
            nbar: "Nama Barang",
            jm: "Jumlah",
            hj: "Harga Jual Barang",
            tpi: "Total per-ID Barang",
            jmter: "Jumlah Tersedia",
            tb: "Tambah Baris",
            hb: "Hapus Baris",
            sm: "Simpan",
            hbb: "Harga Beli Barang",
            ttj: "Total Penjualan",
            ttsj: "Total Sedia Jual",
            ttb: "Total Pembelian",
            ttab: "Total barang Dibeli",
            ttnb: "Total Nilai Dibeli",
            ttaj: "Total barang Dijual",
            ttnj: "Total Nilai Dibeli",
            nmt: "No. Transaksi:",
            tgl: "Tanggal:",
            nmt2: "No. Transaksi:",
            tgl2: "Tanggal:",
            dtbr1: "* Jumlah barang tersimpan otomatis 0 unit saat data barang pertama kali dibuat",
            dtbr2: "* Total jumlah dibeli akan terhitung otomatis 0 unit saat data barang pertama kali dibuat",
            dtbr3:  "* Total dibeli akan terhitung otomatis 0 saat data barang pertama kali dibuat",
            dtbr4: "* Total jumlah dijual akan terhitung otomatis 0 unit saat data barang pertama kali dibuat",
            dtbr5: "* Total dijual akan terhitung otomatis 0 saat data barang pertama kali dibuat"
        },
        {
            hrmi: "Sunday",
            hrse: "Monday",
            hrsel: "Tuesday",
            hrrb: "Wednesday",
            hrkm: "Thursday",
            hrju: "Friday",
            hrsa: "Saturday",
            stok: "Stock",
            pembelian: "Purchase",
            penjualan: "Sales",
            dtbrg: "Data Items",
            rkmn: "Record",
            rcpem: "Purchase Record",
            rcpen: "Sales Record",
            mskn: "Input",
            ibar: "Item ID",
            nbar: "Item Name",
            jm: "Amount",
            hj: "Item Selling Price",
            tpi: "Total per-Item ID",
            jmter: "Amount Available",
            tb: "Add Line",
            hb: "Delete Line",
            sm: "Save",
            hbb: "Item Purchase Price",
            ttj: "Total Sales",
            ttsj: "Total Ready to Sale",
            ttb: "Total Purchase",
            ttab: "Total Amount Purchased",
            ttnb: "Total Value Purchased",
            ttaj: "Total Amount Sold",
            ttnj: "Total Value Sold",
            nmt: "Transaction Number:",
            tgl: "Date:",
            nmt2: "Transaction Number",
            tgl2: "Date",
            dtbr1: "* The number of items stored automatically 0 units when the item data is first created",
            dtbr2: "* Total number of items purchased automatically 0 units when the item data is first created",
            dtbr3: "* Total purchase automatically 0 when the item data is first created",
            dtbr4: "* Total number of items sold automatically 0 units when the item data is first created",
            dtbr5: "* Total sales automatically 0 when the item data is first created"
        }
    ]
